name: Deploy App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

    - name: Build Docker image
      run: |
        cd app
        docker build -t myapp:${{ github.sha }} .

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region <sa-east-1> | docker login --username AWS --password-stdin <757330634377>.dkr.ecr.<sa-east-1>.amazonaws.com

    - name: Push Docker image to Amazon ECR
      run: |
        docker tag myapp:${{ github.sha }} <757330634377>.dkr.ecr.<sa-east-1>.amazonaws.com/myapp:${{ github.sha }}
        docker push <account-id>.dkr.ecr.<sa-east-1>.amazonaws.com/myapp:${{ github.sha }}

   
